// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiLzVH5zUIHRF4MZKx1T5qD5GoX-6-yhM',
    appId: '1:213751056335:web:458fcdc490bdc48160f4ba',
    messagingSenderId: '213751056335',
    projectId: 'x-o-game-16-7-2025',
    authDomain: 'x-o-game-16-7-2025.firebaseapp.com',
    storageBucket: 'x-o-game-16-7-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jRfYeC0U0MWKozsg-9eFSJ-VIHBqvIg',
    appId: '1:213751056335:android:1d98b741f097211660f4ba',
    messagingSenderId: '213751056335',
    projectId: 'x-o-game-16-7-2025',
    storageBucket: 'x-o-game-16-7-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMfyd90GRpen2iEqR8FQ8cNADX-ZnE7o',
    appId: '1:213751056335:ios:932c7fa2d709ad2160f4ba',
    messagingSenderId: '213751056335',
    projectId: 'x-o-game-16-7-2025',
    storageBucket: 'x-o-game-16-7-2025.firebasestorage.app',
    iosBundleId: 'com.example.xOGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMfyd90GRpen2iEqR8FQ8cNADX-ZnE7o',
    appId: '1:213751056335:ios:932c7fa2d709ad2160f4ba',
    messagingSenderId: '213751056335',
    projectId: 'x-o-game-16-7-2025',
    storageBucket: 'x-o-game-16-7-2025.firebasestorage.app',
    iosBundleId: 'com.example.xOGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiLzVH5zUIHRF4MZKx1T5qD5GoX-6-yhM',
    appId: '1:213751056335:web:bbf43034c5519eb260f4ba',
    messagingSenderId: '213751056335',
    projectId: 'x-o-game-16-7-2025',
    authDomain: 'x-o-game-16-7-2025.firebaseapp.com',
    storageBucket: 'x-o-game-16-7-2025.firebasestorage.app',
  );
}
